### ISSUE TITLE
onStartInstall(2)

### ISSUE THREAD

**Issue by zhaozhangyun** [googlesamples/android-dynamic-features#2] opened 2018-05-15 09:13 UTC
05-15 17:07:21.599 31171 31171 I PlayCore: UID: [10488]  PID: [31171] SplitInstallListenerRegistry : registerListener
05-15 17:07:27.149 31171 31171 I PlayCore: UID: [10488]  PID: [31171] SplitInstallManagerImpl : App has no applicationInfo or metaData
05-15 17:07:27.152 31171 31171 I PlayCore: UID: [10488]  PID: [31171] SplitInstallManagerImpl : App has no applicationInfo or metaData
05-15 17:07:27.155 31171 31171 I PlayCore: UID: [10488]  PID: [31171] SplitInstallService : startInstall([assets])
05-15 17:07:27.160 31171 31308 I PlayCore: UID: [10488]  PID: [31171] SplitInstallService : Initiate binding to the service.
05-15 17:07:27.202 31171 31171 I PlayCore: UID: [10488]  PID: [31171] SplitInstallService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.splitinstallservice.SplitInstallService})
05-15 17:07:27.205 31171 31308 I PlayCore: UID: [10488]  PID: [31171] SplitInstallService : linkToDeath
05-15 17:07:27.278 31171 31308 I PlayCore: UID: [10488]  PID: [31171] SplitInstallService : Unbind from service.
05-15 17:07:27.278 31171 31184 I PlayCore: UID: [10488]  PID: [31171] SplitInstallService : onStartInstall(2)
05-15 17:07:43.948 31171 31171 I PlayCore: UID: [10488]  PID: [31171] SplitInstallListenerRegistry : unregisterListener

**Comment by keyboardsurfer** [comment] 2018-05-16 22:59
Please add some more context. Is this happening to you with the given sample or with your own implementation?

**Comment by zhaozhangyun** [comment] 2018-05-17 05:09
I’m trying on the given sample on my device with Oreo API level and using GooglePlay v9.8.

The error log include [onError(-2)]


发送自 Zizzy’s Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by keyboardsurfer** [comment] 2018-05-21 13:57
Duplicate of #1

**Closed by keyboardsurfer** 2018-05-21 13:57 UTC

**Comment by zhaozhangyun** [comment] 2018-05-22 06:48
I've been able to run successfully on the Android emulator with Sdk API on 27, but failed with on 26.

发送自 Zizzy’s Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by keyboardsurfer** [comment] 2018-05-22 15:40
9.8 is quite dated by now. Please update GooglePlayServices to a more recent version.

**Comment by zhaozhangyun** [comment] 2018-05-23 01:19
Thanks for your help.

发送自 Zizzy’s Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
