### ISSUE TITLE
Problem with the instalation

### ISSUE THREAD

**Issue by DilerxD** [googlesamples/android-dynamic-features#7] opened 2018-05-29 00:24 UTC
Hi, i use bundletool for the instalation of the apks but i dont see the on demand feature when i use the application, this happens to me with my app. 
Helppppp. :(

**Comment by saurabhkpatel** [comment] 2018-05-29 21:56
Which steps are you following to tests?

**Comment by saurabhkpatel** [comment] 2018-05-31 16:39
@DilerxD What do you want to test? Can you please explain in the detail?
Which on demand feature is missing? Share the video for it.

**Comment by keyboardsurfer** [comment] 2018-06-07 11:05
According to your configuration all feature modules will be deployed to the device.
Does the Android Studio configuration work as intended?

**Comment by kavyabhat** [comment] 2018-09-05 11:40
While building the apks with the `build-apks` command, did you also provide the flags `--ks` and `--ks-key-alias` ? I believe the downloading of the dynamic feature modules happens only with signed apks.

**Comment by asthagarg2428** [comment] 2018-09-23 17:04
> you're doing the right steps to install the apk. All modules should be available.
> @DilerxD What do you want to test? Can you please explain in the detail?
> Which on demand feature is missing? Share the video for it.

I tried running this sample application  and found that I'm never getting the log "Already installed" which is put in the condition if 'manager has the module name in the installed module names'.
I tried this using signed bundle and single apk using following command-
To build signed apks (ignore the project name)-
java -jar ~/Downloads/bundletool-all-0.5.1.jar build-apks --bundle=Documents/CalC/app/build/outputs/bundle/debug/app.aab --output=Documents/my_signed_for_device.apks --ks=Documents/MyKey.jks --ks-key-alias=key --connected-device

To run on connected device-
java -jar ~/Downloads/bundletool-all-0.5.1.jar install-apks --apks=my_signed_for_device.apks

Is it not caching the downloaded modules ? or am I missing any step?

**Comment by carlosgub** [comment] 2018-09-25 03:42
@keyboardsurfer @asthagarg2428, @keyboardsurfer is correct, the only way to try this is uploading the app to the google play console with a different package name.

Ty to all .

**Comment by moisesvs** [comment] 2018-09-28 08:20
Hi everybody,

I tried do this but I had the same problems. I deselected several modules but when Android is ready to download it I receive the following exception:

        // Load and install the requested feature module.
        manager.startInstall(request)
                .addOnSuccessListener {
                    Log.v("TAG", "Install finished 100%")
                }.addOnFailureListener {
                    Log.e("TAG", "Error install module")
                    Log.e("TAG", it.message, it.cause)
                }

The exception which I receive is: Split Install Error: -2 
How could I avoid this exception? I don't have any idea about the topic... 

Thanks a lot ;)

**Comment by pfmaggi** [comment] 2018-09-28 10:05
@moisesvs what do you mean with "I've deselected several modules"?
Are you testing the application through the Play Store (with a different package name)?

**Comment by keyboardsurfer** [comment] 2018-09-28 11:10
You have to make sure that the keys for singing the apks that you are installing on the device match the one's that you used for uploading to the PlayStore.
I'd recommend downloading directly from the PlayStore and then downloading the feature-modules.

**Comment by moisesvs** [comment] 2018-10-01 10:58
Thanks for your comments. 

Right now, I heven't uploaded my app with dynamic features to Google Play. I thought that I could tester that feature into local device.

Could I test this in my device? Or not? In the future I could test it?

**Comment by carlosgub** [comment] 2018-10-01 13:05
hI @moisesvs, really for now uploading to google play is the only way to prove it. I suppose later Google will put a offline testing of this feature.

Cheers.

**Comment by yibinstudio** [comment] 2018-11-14 15:16
hi,there is something wrong when i try to upload the app.aab to google play.So i use bundletool to build-apks by the app.abb,the command line print the error message like this,Android App Bundle Buid Error<fusing> element is missing the 'include' attribute (split: 'kotlin'),but i check the manifest file ,there is a 'include' attribute behind 'fusing', so i am confused.

**Comment by carlosgub** [comment] 2018-11-14 19:31
@yibinstudio I got the same error, but can you put all the error that the bundletool give you to help you :D ?

**Comment by yibinstudio** [comment] 2018-11-15 02:18
> the bun
the error message like tihis:
[BT:0.3.3] Error: <fusing> element is missing the 'include' attribute (split: 'kotlin').
com.android.tools.build.bundletool.exceptions.manifest.ManifestFusingException$FusingMissingIncludeAttribute: <fusing> element is missing the 'include' attribute (split: 'kotlin').
	at com.android.tools.build.bundletool.manifest.AndroidManifest.lambda$null$4(AndroidManifest.java:178)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.android.tools.build.bundletool.manifest.AndroidManifest.lambda$getIsModuleIncludedInFusing$5(AndroidManifest.java:178)
	at java.util.Optional.map(Optional.java:215)
	at com.android.tools.build.bundletool.manifest.AndroidManifest.getIsModuleIncludedInFusing(AndroidManifest.java:175)
	at com.android.tools.build.bundletool.validation.AndroidManifestValidator.validateFusingConfig(AndroidManifestValidator.java:63)
	at com.android.tools.build.bundletool.validation.AndroidManifestValidator.validateModule(AndroidManifestValidator.java:35)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.lambda$validateBundleModules$5(ValidatorRunner.java:68)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:406)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundleModules(ValidatorRunner.java:68)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundle(ValidatorRunner.java:55)
	at com.android.tools.build.bundletool.validation.AppBundleValidator.validate(AppBundleValidator.java:71)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.executeWithTempDir(BuildApksCommand.java:258)
	at com.android.tools.build.bundletool.io.TempFiles.withTempDirectoryReturning(TempFiles.java:51)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:245)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:72)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:44)

And  I  check the manifest file ,the fusing attribute and include attribute is correct:
<dist:module
        dist:onDemand="true"
        dist:title="@string/module_feature_kotlin">
        <dist:fusing dist:include="true" />
    </dist:module>

**Comment by keyboardsurfer** [comment] 2019-05-21 15:10
You can now use Internal App Sharing to test the installation quickly.
The issue you're describing will be fixed in the next sample push.

**Comment by moisesvs** [comment] 2019-05-23 10:16
Do you know where could I find any information about App Sharing in Google Play to test the dynamic features in my app?

**Comment by keyboardsurfer** [comment] 2019-05-23 11:00
[That's the article you want to be looking at.](https://support.google.com/googleplay/android-developer/answer/9303479?hl=en)

**Closed** 2019-07-04 17:16 UTC
