### ISSUE TITLE
ERROR: Could not GET 'httpmime-4.5.6.pom'. Received status code 502 from server: Bad Gateway Enable Gradle 'offline mode' and sync project

### ISSUE THREAD

**Issue by Dewsworld** [googlesamples/android-dynamic-features#37] opened 2019-03-21 09:33 UTC
ERROR: Could not GET 'https://jcenter.bintray.com/org/apache/httpcomponents/httpmime/4.5.6/httpmime-4.5.6.pom'. Received status code 502 from server: Bad Gateway
Enable Gradle 'offline mode' and sync project

**Comment by Dewsworld** [comment] 2019-03-21 09:34
Enabling offline creates the issue below.
ERROR: No cached version of org.apache.httpcomponents:httpmime:4.5.6 available for offline mode.
Disable Gradle 'offline mode' and sync project

**Comment by pfmaggi** [comment] 2019-03-21 11:30
Thanks for reporting this.
I'm closing this issue because I cannot reproduce it.

Please reopen if you still think this is an issue with the sample and you can provide some reproduction steps.

**Closed by pfmaggi** 2019-03-21 11:30 UTC
