### ISSUE TITLE
SplitInstallService : onError(-2)

### ISSUE THREAD

**Issue by daimonkor** [googlesamples/android-dynamic-features#1] opened 2018-05-14 13:19 UTC
```
PlayCore: UID: [10177]  PID: [25469] SplitInstallManagerImpl : App has no applicationInfo or metaData
05-14 16:17:14.120 25469-25469/com.google.android.samples.dynamicapps.ondemand I/PlayCore: UID: [10177]  PID: [25469] SplitInstallManagerImpl : App has no applicationInfo or metaData
05-14 16:17:14.121 25469-25469/com.google.android.samples.dynamicapps.ondemand I/PlayCore: UID: [10177]  PID: [25469] SplitInstallService : startInstall([java])
05-14 16:17:14.121 25469-25825/com.google.android.samples.dynamicapps.ondemand I/PlayCore: UID: [10177]  PID: [25469] SplitInstallService : Initiate binding to the service.
05-14 16:17:14.136 25469-25469/com.google.android.samples.dynamicapps.ondemand I/PlayCore: UID: [10177]  PID: [25469] SplitInstallService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.splitinstallservice.SplitInstallService})
05-14 16:17:14.137 25469-25825/com.google.android.samples.dynamicapps.ondemand I/PlayCore: UID: [10177]  PID: [25469] SplitInstallService : linkToDeath
05-14 16:17:14.182 25469-25481/com.google.android.samples.dynamicapps.ondemand I/PlayCore: UID: [10177]  PID: [25469] SplitInstallService : onError(-2)
05-14 16:17:14.182 25469-25825/com.google.android.samples.dynamicapps.ondemand I/PlayCore: UID: [10177]  PID: [25469] SplitInstallService : Unbind from service.
```

What is the error "onError(-2)"? Thanks for help.

**Comment by keyboardsurfer** [comment] 2018-05-22 15:43
On #2 we discussed that the PlayServices version (9.8) should be updated.
I can not reproduce this issue with a recent version of PlayServices on either supported device or emulator with supported API level.

Please provide more information (API level and PlayServices version you're running) to help debug this issue.

**Comment by keyboardsurfer** [comment] 2018-05-24 11:42
As long as you are working locally, the sample should behave correctly and you can safely ignore this error.
Is this error message causing issues to any of you?

**Comment by saurabhkpatel** [comment] 2018-05-24 16:43
@keyboardsurfer: I think we can't test it locally, right? If that's true for this sample application then it's fine.
Actually, I didn't face any crash but it was just trying to load the dynamic module with the infinite progress bar.

**Comment by keyboardsurfer** [comment] 2018-05-24 16:47
Did you upload a version of the sample to the PlayStore and were receiving the error from the uploaded version?

**Comment by saurabhkpatel** [comment] 2018-05-24 17:15
@keyboardsurfer: No. I've uploaded it. I thought it would work locally but later I read on the android developers website that it's not possible to test without uploading it to google play console.

**Comment by keyboardsurfer** [comment] 2018-05-25 10:04
@saurabhkpatel It's correct that local development currently installs all apks and does not emulate loading modules.

@coderEvolve the official sample is not uploaded to the PlayStore at this point. You'll have to upload a version on your own.

**Comment by keyboardsurfer** [comment] 2018-05-25 10:13
@saurabhkpatel I can't seem to reproduce the error, but you're trying to load a module that doesn't exist. If you think that this is an issue with the API, please [file an issue against it](https://issuetracker.google.com/issues/new?component=384531).

**Comment by coderEvolve** [comment] 2018-05-25 11:10
@keyboardsurfer 
![948b7 o06 ncbsaks o_ 0y](https://user-images.githubusercontent.com/38391014/40541665-4c8becec-604f-11e8-8e46-2d7b5efd4ccb.png)

**Comment by saurabhkpatel** [comment] 2018-05-25 16:11
@keyboardsurfer I'll revisit my test steps. I think I misunderstood the testing process here. I'll update this thread if I'll face the problem again.
Thanks again.

**Comment by keyboardsurfer** [comment] 2018-06-07 11:10
Closing this for now. Please comment if the issue persists and we'll re-open.

**Closed by keyboardsurfer** 2018-06-07 11:10 UTC

**Comment by agicquel** [comment] 2018-07-26 10:02
I agree with @saurabhkpatel the testing process is quite obscure. Do I need to upload to test my modules ?

**Comment by keyboardsurfer** [comment] 2018-07-26 10:05
@agicquel I don't recommend testing the actual download flow in integration tests, as this would rely on a service which is not in your control. You could mock the listener and check that your different paths are hit and behave as intended.

**Comment by agicquel** [comment] 2018-07-26 10:36
@keyboardsurfer Actually you can control the listeners of the manager when a new module is installed or if the installation failed. I just want to check the integration of the module installation into my current UI, and how I can launch the fragment inside the dynamic feature. Furthermore, I want to test the behavior when a module is included or installed later.

**Comment by keyboardsurfer** [comment] 2018-07-26 10:42
In that case you'll have to upload to the PlayStore to actually see what happens, @agicquel.

**Comment by agicquel** [comment] 2018-07-26 11:55
@keyboardsurfer Understood ! Do you plan to include this kind of test into the bundletool ?
